language: python

python:
  - "2.7"
  - "3.4"

# whitelist
branches:
    only:
        - master
        - develop

# install system dependencies
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libhdf5-serial-dev

# install python dependencies
install:
  - pip install codecov
  - pip install pytest-cov
  - pip install pytest-pep8
  - pip install numpy numexpr Cython
  - pip install tables
  - pip install scandir
  - pip install -e .

# run tests
script: 
  - py.test --cov datreant --pep8 datreant tests/

after_success:
  - codecov
