language: python
sudo: false

addons:
  apt:
    packages:
    - libhdf5-serial-dev

python:
  - "2.7"

# whitelist
branches:
    only:
        - master
        - develop

# install python dependencies
install:
  - pip install codecov
  - pip install pytest-cov
  - pip install pytest-pep8
  - pip install numpy numexpr Cython
  - pip install tables
  - pip install pandas h5py
  - pip install scandir
  - pip install yaml
  - pip install -e .

# run tests
script: 
  - py.test --cov datreant --pep8 datreant

after_success:
  - codecov
