language: python
sudo: false

python:
  - "2.7"
  - "3.4"

# whitelist
branches:
    only:
        - master
        - develop

# install python dependencies
install:
  - pip install codecov
  - pip install pytest-cov
  - pip install pytest-pep8
  - pip install numpy numexpr Cython
  - pip install tables
  - pip install pandas h5py
  - pip install scandir
  - pip install -e .

# run tests
script: 
  - py.test --cov datreant --pep8 datreant tests/

after_success:
  - codecov
